name: task_manager
description: A comprehensive task management Android app with multi-calendar support, notes, and reminder features.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  table_calendar: ^3.0.9
  flutter_colorpicker: ^1.0.3
  flutter_quill: ^11.2.0
  cached_network_image: ^3.2.3
  intl: ^0.19.0
  uuid: ^4.5.1
  nepali_utils: ^3.0.3
  google_maps_flutter: ^2.3.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  contacts_service: ^0.6.3
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.4.1
  url_launcher: ^6.1.11
  permission_handler: ^11.3.1
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic